use_frameworks!

platform :ios, '8.0'

target 'chenyubuchongfu_Example' do
  pod 'chenyubuchongfu', :path => '../'

  target 'chenyubuchongfu_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
